[package]
name = "custom_hash_func"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name     = "hash_bench"   # matches benches/hash_bench.rs
harness  = false          # <-- this is the crucial line